project:
  type: website
  output-dir: docs
  
website:
  title: "Geotechnical Student Organization"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - donate.qmd
      - events.qmd
    tools:
      - icon: instagram
        text: Instagram
        href: https://instagram.com/gso_umaine
      - icon: github
        text: Github
        href: https://github.com/sabacyr
      - icon: linkedin
        text: LinkedIn
        href: http://linkedin.com/gso-me
  page-footer:
    right: "Built with [Quarto](https://quarto.org/)"
    left: "&copy; Copyright 2026, Saba Cyr"

format:
  html:
    theme: cerulean
    toc: true

editor: source

