project:
  type: website

website:
  title: "Geotechnical Student Organization"
  favicon: img/favicon.png
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: events.qmd
        text: Events
      - href: resources.qmd
        text: Resources
      - href: gallery.qmd
        text: Gallery
      - href: members.qmd
        text: Members
      - href: contact.qmd
        text: Contact Us
      - href: donate.qmd
        text: Donate

    right:
      - icon: instagram
        href: https://instagram.com/gso_umaine
      - icon: linkedin
        href: https://linkedin.com/gso-me
      - icon: github
        href: https://github.com/sabacyr

format:
  html:
    theme: cosmo
    css: styles.css
    toc: false
